# thanks
# https://github.com/shunkakinoki/shunkakinoki/blob/main/.github/workflows/notion.yml

name: Notion

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install --frozen-lockfile
      - run: bash scripts/notion2md.sh
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      - continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "auto notion update"
          git push
